spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parc_oto?useSSL=false&serverTimezone=UTC
    username: root
    password: parcotoDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
