spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parc_oto_db
    username: root
    password: parcotoDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
